import { buildReportFilename, buildEntityReportFilename } from './reportFilenames.js'
import { downloadBlob } from './downloadFile.js'

const DISCLAIMER_TEXT = 'Disclaimer: This report is automatically generated by the Internal IT Dashboard for internal informational and reporting purposes. Data is based on the latest successfully retrieved or imported source data available at the time of report generation. Please verify critical information with the respective source system before making business or licensing decisions.'

// Appended to the sectioned (human-readable, multi-table) CSV exports only —
// NOT to the flat single-dataset export below, whose own comment/purpose is
// to stay a clean, directly re-importable table for further analysis; a
// disclaimer section there would break that.
function disclaimerSection(generatedAt) {
  return { title: 'Report Info', rows: [{ Report: 'Internal IT Dashboard', 'Generated on': new Date(generatedAt).toLocaleString(), Disclaimer: DISCLAIMER_TEXT }] }
}

function csvEscape(v) {
  if (v === null || v === undefined) return ''
  return '"' + String(v).replace(/"/g, '""') + '"'
}

// Multi-section CSV: a single file with a "## Section" heading line before
// each table, since a single-entity export (one user, one application)
// naturally has several small, differently-shaped tables rather than one
// flat dataset. Every value passed through csvEscape.
function sectionedCsv(sections) {
  const lines = []
  for (const section of sections) {
    lines.push(`## ${section.title}`)
    if (!section.rows.length) {
      lines.push(section.emptyMessage || 'No data available.')
      lines.push('')
      continue
    }
    const keys = Object.keys(section.rows[0])
    lines.push(keys.join(','))
    for (const row of section.rows) lines.push(keys.map((k) => csvEscape(row[k])).join(','))
    lines.push('')
  }
  return lines.join('\n')
}

// CSV keeps a single flat shape (unlike PDF/Excel it can't mix a summary
// block with a table), so it exports the report's underlying dataset —
// every filtered/complete record, ready for further analysis in any tool.
export function buildCsvText(reportModel) {
  const rows = reportModel.dataset || []
  if (!rows.length) return ''
  const keys = Object.keys(rows[0]).filter((k) => !k.startsWith('_'))
  const escape = (v) => {
    if (v === null || v === undefined) return ''
    return '"' + String(v).replace(/"/g, '""') + '"'
  }
  const lines = [keys.join(',')]
  rows.forEach((r) => lines.push(keys.map((k) => escape(r[k])).join(',')))
  return lines.join('\n')
}

export function downloadCsvReport(reportModel, prefix = 'Internal_IT_Usage_Report') {
  const csv = buildCsvText(reportModel)
  const blob = new Blob([csv], { type: 'text/csv' })
  const filename = buildReportFilename({ prefix, scope: reportModel.scope, filters: reportModel.rawFilters, ext: 'csv' })
  downloadBlob(blob, filename)
  return filename
}

export function downloadMicrosoftUserCsv(model) {
  const p = model.profile
  const csv = sectionedCsv([
    { title: 'Profile', rows: [{
      'Display Name': p.display_name || 'N/A', 'Email / UPN': p.upn || 'N/A', 'User ID': p.ms_id || 'N/A',
      'Job Title': p.job_title || 'N/A', Department: p.department || 'N/A', Company: p.company_name || 'N/A',
      Office: p.office_location || 'N/A', Domain: p.domain || 'N/A', 'Account Status': p.account_enabled ? 'Enabled' : 'Disabled',
      Manager: p.manager_display_name || 'N/A', 'VBU / Organization': p.vbu || 'N/A'
    }] },
    { title: 'Assigned Licenses', rows: model.licenses.map((l) => ({ License: l.sku_part_number || 'N/A' })), emptyMessage: 'No licenses assigned.' },
    { title: 'Copilot Usage', rows: model.copilot ? [{ 'Usage (Activity)': model.copilot.activity_count ?? 'N/A', 'Last Active': model.copilot.last_activity || 'N/A', Plan: model.copilot.plan || 'N/A' }] : [], emptyMessage: 'No Copilot usage data available for this user.' },
    { title: 'Devices', rows: model.devices.map((d) => ({ Device: d.device_name || 'N/A', OS: d.operating_system || 'N/A', Compliance: d.compliance_state || 'N/A', 'Management State': d.management_state || 'N/A', 'Last Sync': d.last_sync_at || 'N/A' })), emptyMessage: 'No devices assigned to this user.' },
    { title: 'Applications', rows: model.applications.map((a) => ({ Application: a.display_name || 'N/A', Version: a.version || 'N/A', Device: (a.devices || []).join(', ') || 'N/A' })), emptyMessage: model.applicationsError ? `Application data unavailable: ${model.applicationsError}` : 'No application data available.' },
    { title: 'Recent Sign-ins', rows: model.signIns.slice(0, 20).map((s) => ({ Time: s.created_at || 'N/A', Application: s.app_display_name || 'N/A', Status: s.status || 'N/A' })), emptyMessage: 'No sign-in activity synced.' },
    disclaimerSection(model.generatedAt)
  ])
  const filename = buildEntityReportFilename({ prefix: 'Internal_IT_M365_User', name: p.display_name || p.upn || 'User', ext: 'csv' })
  downloadBlob(new Blob([csv], { type: 'text/csv' }), filename)
  return filename
}

export function downloadMicrosoftApplicationCsv(model) {
  const s = model.summary
  const csv = sectionedCsv([
    { title: 'Application Overview', rows: [{
      Application: s.displayName, 'Publisher(s)': s.publishers.join(', ') || 'N/A', 'Platform(s)': s.platforms.join(', ') || 'N/A',
      'Total Device Installs': s.totalDeviceCount, 'Detected Versions': s.versionCount,
      'Unique Devices Linked': s.uniqueLinkedDeviceCount, 'Last Synced': s.lastSyncedAt || 'N/A'
    }] },
    { title: 'Version Breakdown', rows: model.versions.map((v) => ({ Version: v.version || 'N/A', 'Device Count': v.deviceCount, Percentage: v.percentage != null ? v.percentage + '%' : 'N/A' })) },
    { title: 'Device Installation Details', rows: model.devices.map((d) => ({ Device: d.device_name || 'N/A', Version: d.application_version || 'N/A', User: d.user_principal_name || 'N/A', OS: d.operating_system || 'N/A', Compliance: d.compliance_state || 'N/A', 'Management State': d.management_state || 'N/A', 'Last Sync': d.last_sync_at || 'N/A' })), emptyMessage: 'No device-level installation records linked yet for this application.' },
    disclaimerSection(model.generatedAt)
  ])
  const filename = buildEntityReportFilename({ prefix: 'Internal_IT_M365_Application', name: s.displayName, ext: 'csv' })
  downloadBlob(new Blob([csv], { type: 'text/csv' }), filename)
  return filename
}
