import * as XLSX from 'xlsx'
import { buildReportFilename, buildEntityReportFilename } from './reportFilenames.js'
import { downloadBlob } from './downloadFile.js'
import { neutralizeFormula } from './formulaSafety.js'

function fmtMoney(v) { return v === null || v === undefined ? 'N/A' : v }
function fmtPct(v) { return v === null || v === undefined ? 'N/A' : v + '%' }

// Security-audit fix (CSV/Excel formula injection, CWE-1236): every sheet
// below is ultimately built from Microsoft Graph profile data, Freshservice
// records, or a manually-uploaded CSV — none of it generated by this app —
// so a directory field (Department, Application/Version, a manual import
// column, ...) could contain a string starting with =, +, -, or @, which
// Excel/LibreOffice/Google Sheets treats as the start of a formula. Rather
// than trust every individual sheet-builder above to remember to escape
// its own fields, these two thin wrappers around XLSX.utils.json_to_sheet/
// aoa_to_sheet are the ONLY way this file ever hands rows to xlsx — see
// their call sites below (jsonSheet/aoaSheet replace every direct
// XLSX.utils.*_to_sheet call in this file).
function sanitizeRows(rows) {
  return rows.map((row) => (
    Array.isArray(row)
      ? row.map(neutralizeFormula)
      : Object.fromEntries(Object.entries(row).map(([k, v]) => [k, neutralizeFormula(v)]))
  ))
}
function jsonSheet(rows) { return XLSX.utils.json_to_sheet(sanitizeRows(rows)) }
function aoaSheet(rows) { return XLSX.utils.aoa_to_sheet(sanitizeRows(rows)) }

const DISCLAIMER_TEXT = 'Disclaimer: This report is automatically generated by the Internal IT Dashboard for internal informational and reporting purposes. Data is based on the latest successfully retrieved or imported source data available at the time of report generation. Please verify critical information with the respective source system before making business or licensing decisions.'

// Same disclaimer/branding every generated PDF carries, added as its own
// sheet so the full text stays readable rather than cramped into one cell.
function disclaimerSheet(generatedAt) {
  return aoaSheet([
    ['Internal IT Dashboard'],
    [`Generated on: ${new Date(generatedAt).toLocaleString()}`],
    [],
    [DISCLAIMER_TEXT]
  ])
}

function summarySheet(model) {
  const s = model.executiveSummary
  const rows = [
    ['Report', model.title],
    ['Scope', model.scope === 'filtered' ? 'Filtered' : 'Complete Dataset'],
    ['Generated', new Date(model.generatedAt).toLocaleString()],
    ['Data Last Updated', model.dataLastUpdated ? new Date(model.dataLastUpdated).toLocaleString() : 'N/A'],
    ['Filters Applied', model.filtersApplied.length ? model.filtersApplied.join('; ') : 'None'],
    [],
    ['Total Users', s.totalUsers],
    ['Total Licenses', s.totalLicenses],
    ['Active Licenses', s.activeLicenses],
    ['Unused Licenses', s.unusedLicenses],
    ['License Utilization', fmtPct(s.utilization)],
    ['Total Spend', fmtMoney(s.totalSpend)],
    ['Potential Savings', fmtMoney(s.potentialSavings)],
    ['Connected Sources', s.connectedSources ?? 'N/A'],
    // Cost report-only field (buildCostReportModel) — absent everywhere else.
    ...(model.lowUsageCost !== undefined ? [['Low-Usage License Cost', fmtMoney(model.lowUsageCost)]] : [])
  ]
  return aoaSheet(rows)
}

function breakdownSheet(rows, nameLabel) {
  const data = rows.map((r) => ({
    [nameLabel]: r.name,
    Users: r.users,
    Licenses: r.licenses,
    'Active Licenses': r.activeLicenses,
    'Utilization %': r.utilization ?? 'N/A',
    Spend: r.spend ?? 'N/A',
    Usage: r.usage,
    ...(r.potentialSavings !== undefined ? { 'Potential Savings': r.potentialSavings ?? 'N/A' } : {})
  }))
  return jsonSheet(data)
}

function usersSheet(dataset) {
  const rows = dataset.map((r) => ({
    Name: r.name, Email: r.email || 'N/A', Department: r.department || 'N/A', Product: r.product || 'N/A',
    Plan: r.plan || 'N/A', Role: r.role || 'N/A', 'License Status': r.license_status || 'N/A',
    Usage: r.activity_count ?? 'N/A', 'Last Active': r.last_activity || 'N/A', Status: r.usage_status || 'N/A',
    // Same centralized cost engine figure the dashboard uses (server/
    // services/costEngine.js) — never independently recalculated here.
    // Original amount/currency alongside the converted reporting-currency
    // figure and the exact FX rate/date used, so the conversion is
    // auditable (Part 7 of the FX spec this implements) rather than only
    // showing the final converted number.
    'Original Amount': r.monthly_cost ?? 'N/A', 'Original Currency': r.currency || 'N/A',
    Cost: r.display_cost ?? 'N/A', Currency: r.display_currency || 'N/A',
    'FX Rate': r.exchange_rate ?? (r.currency && r.display_currency && r.currency === r.display_currency ? 1 : 'N/A'),
    'FX Rate Date': r.exchange_rate_date || 'N/A',
    'Cost Type': r.cost_label || 'N/A', 'Cost Source': r.cost_source || 'N/A'
  }))
  return jsonSheet(rows)
}

function activitySheet(activitySummary) {
  if (!activitySummary.length) return aoaSheet([['No activity metrics available from the current data sources.']])
  return jsonSheet(activitySummary.map((a) => ({ Metric: a.label, Total: a.total })))
}

export function buildExcelWorkbook(model) {
  const wb = XLSX.utils.book_new()
  XLSX.utils.book_append_sheet(wb, summarySheet(model), 'Executive Summary')
  XLSX.utils.book_append_sheet(wb, breakdownSheet(model.providerBreakdown, 'Provider'), 'Provider Overview')
  XLSX.utils.book_append_sheet(wb, breakdownSheet(model.productBreakdown, 'Product'), 'Product Analysis')
  XLSX.utils.book_append_sheet(wb, breakdownSheet(model.departmentBreakdown, 'Department'), 'Department Analysis')
  // VBU/domain/plan breakdowns only exist on the Cost report's model
  // (buildCostReportModel) — skipped entirely for every other report.
  if (model.vbuBreakdown?.length) XLSX.utils.book_append_sheet(wb, breakdownSheet(model.vbuBreakdown, 'VBU'), 'VBU Analysis')
  if (model.domainBreakdown?.length) XLSX.utils.book_append_sheet(wb, breakdownSheet(model.domainBreakdown, 'Domain'), 'Domain Analysis')
  if (model.planBreakdown?.length) XLSX.utils.book_append_sheet(wb, breakdownSheet(model.planBreakdown, 'Plan'), 'License / Plan Analysis')
  XLSX.utils.book_append_sheet(wb, usersSheet(model.dataset), 'Users')
  XLSX.utils.book_append_sheet(wb, activitySheet(model.activitySummary), 'AI Activity')
  XLSX.utils.book_append_sheet(wb, disclaimerSheet(model.generatedAt), 'Disclaimer')
  return wb
}

export function downloadExcelReport(reportModel, prefix = 'Internal_IT_Usage_Report') {
  const wb = buildExcelWorkbook(reportModel)
  const arrayBuffer = XLSX.write(wb, { bookType: 'xlsx', type: 'array' })
  const blob = new Blob([arrayBuffer], { type: 'application/octet-stream' })
  const filename = buildReportFilename({ prefix, scope: reportModel.scope, filters: reportModel.rawFilters, ext: 'xlsx' })
  downloadBlob(blob, filename)
  return filename
}

function writeWorkbook(wb, filename) {
  const arrayBuffer = XLSX.write(wb, { bookType: 'xlsx', type: 'array' })
  downloadBlob(new Blob([arrayBuffer], { type: 'application/octet-stream' }), filename)
  return filename
}

// ---- Microsoft 365 User Detail export ----
export function buildMicrosoftUserWorkbook(model) {
  const wb = XLSX.utils.book_new()
  const p = model.profile
  XLSX.utils.book_append_sheet(wb, aoaSheet([
    ['Report', model.title], ['Generated', new Date(model.generatedAt).toLocaleString()],
    ['Data Last Updated', model.dataLastUpdated ? new Date(model.dataLastUpdated).toLocaleString() : 'N/A'], [],
    ['Display Name', p.display_name || 'N/A'], ['Email / UPN', p.upn || 'N/A'], ['User ID', p.ms_id || 'N/A'],
    ['Job Title', p.job_title || 'N/A'], ['Department', p.department || 'N/A'], ['Company', p.company_name || 'N/A'],
    ['Office', p.office_location || 'N/A'], ['Domain', p.domain || 'N/A'],
    ['Account Status', p.account_enabled ? 'Enabled' : 'Disabled'],
    ['Manager', p.manager_display_name || 'N/A'], ['VBU / Organization', p.vbu || 'N/A']
  ]), 'Profile')
  XLSX.utils.book_append_sheet(wb, model.licenses.length
    ? jsonSheet(model.licenses.map((l) => ({ License: l.sku_part_number || 'N/A' })))
    : aoaSheet([['No licenses assigned.']]), 'Licenses')
  XLSX.utils.book_append_sheet(wb, model.copilot
    ? aoaSheet([['Usage (Activity)', model.copilot.activity_count ?? 'N/A'], ['Last Active', model.copilot.last_activity || 'N/A'], ['Plan', model.copilot.plan || 'N/A']])
    : aoaSheet([['No Copilot usage data available for this user.']]), 'Copilot')
  XLSX.utils.book_append_sheet(wb, model.devices.length
    ? jsonSheet(model.devices.map((d) => ({ Device: d.device_name || 'N/A', OS: d.operating_system || 'N/A', Compliance: d.compliance_state || 'N/A', 'Management State': d.management_state || 'N/A', 'Last Sync': d.last_sync_at || 'N/A' })))
    : aoaSheet([['No devices assigned to this user.']]), 'Devices')
  XLSX.utils.book_append_sheet(wb, model.applications.length
    ? jsonSheet(model.applications.map((a) => ({ Application: a.display_name || 'N/A', Version: a.version || 'N/A', Device: (a.devices || []).join(', ') || 'N/A' })))
    : aoaSheet([[model.applicationsError ? `Application data unavailable: ${model.applicationsError}` : 'No application data available.']]), 'Applications')
  if (model.signIns.length) {
    XLSX.utils.book_append_sheet(wb, jsonSheet(model.signIns.map((s) => ({ Time: s.created_at || 'N/A', Application: s.app_display_name || 'N/A', Status: s.status || 'N/A' }))), 'Sign-ins')
  }
  XLSX.utils.book_append_sheet(wb, disclaimerSheet(model.generatedAt), 'Disclaimer')
  return wb
}

export function downloadMicrosoftUserExcel(model) {
  const wb = buildMicrosoftUserWorkbook(model)
  return writeWorkbook(wb, buildEntityReportFilename({ prefix: 'Internal_IT_M365_User', name: model.profile.display_name || model.profile.upn || 'User', ext: 'xlsx' }))
}

// ---- Microsoft 365 Application Detail export ----
export function buildMicrosoftApplicationWorkbook(model) {
  const wb = XLSX.utils.book_new()
  const s = model.summary
  XLSX.utils.book_append_sheet(wb, aoaSheet([
    ['Report', model.title], ['Generated', new Date(model.generatedAt).toLocaleString()], [],
    ['Application', s.displayName], ['Publisher(s)', s.publishers.join(', ') || 'N/A'], ['Platform(s)', s.platforms.join(', ') || 'N/A'],
    ['Total Device Installs', s.totalDeviceCount], ['Detected Versions', s.versionCount],
    ['Unique Devices Linked', s.uniqueLinkedDeviceCount], ['Last Synced', s.lastSyncedAt ? new Date(s.lastSyncedAt).toLocaleString() : 'N/A']
  ]), 'Summary')
  XLSX.utils.book_append_sheet(wb, jsonSheet(model.versions.map((v) => ({ Version: v.version || 'N/A', 'Device Count': v.deviceCount, Percentage: v.percentage != null ? v.percentage + '%' : 'N/A' }))), 'Version Breakdown')
  XLSX.utils.book_append_sheet(wb, model.devices.length
    ? jsonSheet(model.devices.map((d) => ({
      Device: d.device_name || 'N/A', Version: d.application_version || 'N/A', User: d.user_principal_name || 'N/A',
      OS: d.operating_system || 'N/A', Compliance: d.compliance_state || 'N/A', 'Management State': d.management_state || 'N/A', 'Last Sync': d.last_sync_at || 'N/A'
    })))
    : aoaSheet([['No device-level installation records linked yet for this application.']]), 'Devices')
  XLSX.utils.book_append_sheet(wb, disclaimerSheet(model.generatedAt), 'Disclaimer')
  return wb
}

export function downloadMicrosoftApplicationExcel(model) {
  const wb = buildMicrosoftApplicationWorkbook(model)
  return writeWorkbook(wb, buildEntityReportFilename({ prefix: 'Internal_IT_M365_Application', name: model.summary.displayName, ext: 'xlsx' }))
}
