import { jsPDF } from 'jspdf'
import autoTable from 'jspdf-autotable'
import { buildReportFilename, buildEntityReportFilename } from './reportFilenames.js'
import { downloadBlob } from './downloadFile.js'
import { getLogoDataUrl, LOGO_ASPECT_RATIO } from './logo.js'

const BRAND_BLUE = [11, 95, 255]
const MARGIN = 14
const PAGE_WIDTH = 210 // A4 mm

// Reserved at the bottom of every page for the footer (rule + disclaimer +
// generated/brand/page-number row) — ensureSpace() and every autoTable call
// below respect this so body content and tables never render into it, and
// a table that spans multiple pages breaks cleanly above the footer rather
// than under it.
const FOOTER_RESERVED_HEIGHT = 32
const AUTO_TABLE_MARGIN = { left: MARGIN, right: MARGIN, bottom: FOOTER_RESERVED_HEIGHT }
const DISCLAIMER_TEXT = 'Disclaimer: This report is automatically generated by the Internal IT Dashboard for internal informational and reporting purposes. Data is based on the latest successfully retrieved or imported source data available at the time of report generation. Please verify critical information with the respective source system before making business or licensing decisions.'

function money(v) { return v === null || v === undefined ? 'N/A' : '$' + Number(v).toLocaleString(undefined, { maximumFractionDigits: 2 }) }
function pct(v) { return v === null || v === undefined ? 'N/A' : v + '%' }
function na(v) { return v === null || v === undefined || v === '' ? 'N/A' : v }
function fmtDate(iso) { return iso ? new Date(iso).toLocaleString() : 'N/A' }

function ensureSpace(doc, y, needed) {
  const pageHeight = doc.internal.pageSize.getHeight()
  if (y + needed > pageHeight - FOOTER_RESERVED_HEIGHT) {
    doc.addPage()
    return 20
  }
  return y
}

function sectionHeading(doc, text, y) {
  y = ensureSpace(doc, y, 14)
  doc.setFontSize(12)
  doc.setTextColor(17, 24, 39)
  doc.setFont(undefined, 'bold')
  doc.text(text, MARGIN, y)
  doc.setFont(undefined, 'normal')
  return y + 6
}

function breakdownTable(doc, title, rows, nameLabel, y, extraCol) {
  if (!rows.length) return y
  y = sectionHeading(doc, title, y)
  const head = [[nameLabel, 'Users', 'Licenses', 'Active', 'Utilization', 'Spend', 'Usage', ...(extraCol ? [extraCol] : [])]]
  const body = rows.map((r) => [
    r.name, r.users, r.licenses, r.activeLicenses, pct(r.utilization), money(r.spend), r.usage.toLocaleString(),
    ...(extraCol ? [money(r.potentialSavings)] : [])
  ])
  autoTable(doc, { startY: y, head, body, margin: AUTO_TABLE_MARGIN, headStyles: { fillColor: BRAND_BLUE }, styles: { fontSize: 9 } })
  return doc.lastAutoTable.finalY + 10
}

// Draws the branded masthead (logo + "Internal IT Dashboard" + report
// title) at the top of the CURRENT page. Async because the logo (the
// existing public/ssp-logo.png asset — never a new/fake image) is fetched
// and base64-encoded on first use; if that fails for any reason, the
// header still renders correctly with text only — a missing logo must
// never break report generation.
async function reportHeader(doc, model) {
  doc.setFillColor(...BRAND_BLUE)
  doc.rect(0, 0, PAGE_WIDTH, 22, 'F')

  let textX = MARGIN
  const logoDataUrl = await getLogoDataUrl()
  if (logoDataUrl) {
    try {
      const logoHeight = 14
      const logoWidth = logoHeight * LOGO_ASPECT_RATIO
      doc.addImage(logoDataUrl, 'PNG', MARGIN, 4, logoWidth, logoHeight)
      textX = MARGIN + logoWidth + 5
    } catch (e) {
      textX = MARGIN // corrupt/unsupported image data — fall back to text-only header
    }
  }

  doc.setTextColor(255, 255, 255)
  doc.setFontSize(9)
  doc.setFont(undefined, 'bold')
  doc.text('Internal IT Dashboard', textX, 10)
  doc.setFont(undefined, 'normal')
  doc.setFontSize(16)
  doc.text(model.title, textX, 18)

  let y = 30
  doc.setTextColor(55, 65, 81)
  doc.setFontSize(9)
  doc.text(`Generated: ${fmtDate(model.generatedAt)}`, MARGIN, y)
  doc.text(`Data last updated: ${fmtDate(model.dataLastUpdated)}`, MARGIN, y + 5)
  doc.text(`Scope: ${model.scope === 'filtered' ? 'Filtered dataset' : 'Complete dataset'} (${model.recordCount.toLocaleString()} records)`, MARGIN, y + 10)
  y += 15

  if (model.sources && model.sources.length) {
    doc.text(`Sources: ${model.sources.map((s) => s.label).join(', ')}`, MARGIN, y)
    y += 5
  }
  if (model.scope === 'filtered' && model.filtersApplied.length) {
    doc.setFont(undefined, 'bold')
    doc.text('Filters Applied:', MARGIN, y)
    doc.setFont(undefined, 'normal')
    y += 5
    model.filtersApplied.forEach((f) => { doc.text(`- ${f}`, MARGIN + 2, y); y += 5 })
  }
  return y + 4
}

// Drawn once, after every page of content already exists, so the total
// page count is known upfront for "Page X of Y" — looping back over every
// page with doc.setPage() rather than trying to draw it page-by-page while
// content is still being added.
function drawFooterOnAllPages(doc, generatedAt) {
  const pageCount = doc.internal.getNumberOfPages()
  const pageHeight = doc.internal.pageSize.getHeight()
  const pageWidth = doc.internal.pageSize.getWidth()
  const footerTop = pageHeight - FOOTER_RESERVED_HEIGHT

  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i)

    doc.setDrawColor(226, 232, 240)
    doc.setLineWidth(0.2)
    doc.line(MARGIN, footerTop, pageWidth - MARGIN, footerTop)

    doc.setFont(undefined, 'normal')
    doc.setFontSize(6.5)
    doc.setTextColor(107, 114, 128)
    const wrapped = doc.splitTextToSize(DISCLAIMER_TEXT, pageWidth - MARGIN * 2)
    doc.text(wrapped, MARGIN, footerTop + 4)

    doc.setFontSize(7.5)
    doc.setTextColor(75, 85, 99)
    doc.text(`Generated on: ${fmtDate(generatedAt)}`, MARGIN, pageHeight - 6)
    doc.text('Internal IT Dashboard', pageWidth / 2, pageHeight - 6, { align: 'center' })
    doc.text(`Page ${i} of ${pageCount}`, pageWidth - MARGIN, pageHeight - 6, { align: 'right' })
  }
}

async function executiveSummaryTable(doc, model, y) {
  y = sectionHeading(doc, 'Executive Summary', y)
  const s = model.executiveSummary
  const body = [
    ['Total Users', s.totalUsers], ['Total Licenses', s.totalLicenses],
    ['Active Licenses', s.activeLicenses], ['License Utilization', pct(s.utilization)],
    ['Total Spend', money(s.totalSpend)], ['Potential Savings', money(s.potentialSavings)],
    ['Unused Licenses', s.unusedLicenses], ['Connected Sources', na(s.connectedSources)],
    // Cost report-only field (src/reports/reportBuilder.js's
    // buildCostReportModel) — absent from every other report's model, so
    // this row simply doesn't appear there.
    ...(model.lowUsageCost !== undefined ? [['Low-Usage License Cost', money(model.lowUsageCost)]] : [])
  ]
  autoTable(doc, { startY: y, body, margin: AUTO_TABLE_MARGIN, styles: { fontSize: 10 }, columnStyles: { 0: { fontStyle: 'bold', cellWidth: 60 } } })
  return doc.lastAutoTable.finalY + 10
}

function userAnalysisTables(doc, model, y) {
  const { topUsers, lowUsage } = model.userAnalysis
  if (topUsers.length) {
    y = sectionHeading(doc, 'Top Users by Usage', y)
    autoTable(doc, {
      startY: y, margin: AUTO_TABLE_MARGIN, headStyles: { fillColor: BRAND_BLUE }, styles: { fontSize: 9 },
      head: [['User', 'Product', 'Usage', 'Spend']],
      body: topUsers.map((u) => [u.name, na(u.product), na(u.activity_count), money(u.display_cost ?? null)])
    })
    y = doc.lastAutoTable.finalY + 10
  }
  if (lowUsage.length) {
    y = sectionHeading(doc, 'Low / No Usage Users', y)
    autoTable(doc, {
      startY: y, margin: AUTO_TABLE_MARGIN, headStyles: { fillColor: BRAND_BLUE }, styles: { fontSize: 9 },
      head: [['User', 'Last Active', 'Product']],
      body: lowUsage.map((u) => [u.name, na(u.last_activity), na(u.product)])
    })
    y = doc.lastAutoTable.finalY + 10
  }
  return y
}

function activityTable(doc, model, y) {
  if (!model.activitySummary.length) return y
  y = sectionHeading(doc, 'AI Activity', y)
  autoTable(doc, {
    startY: y, margin: AUTO_TABLE_MARGIN, headStyles: { fillColor: BRAND_BLUE }, styles: { fontSize: 9 },
    head: [['Metric', 'Total']],
    body: model.activitySummary.map((a) => [a.label, a.total.toLocaleString()])
  })
  return doc.lastAutoTable.finalY + 10
}

export async function buildReportPdf(model) {
  const doc = new jsPDF()
  let y = await reportHeader(doc, model)
  y = await executiveSummaryTable(doc, model, y)
  y = breakdownTable(doc, 'Provider Overview', model.providerBreakdown, 'Provider', y)
  y = breakdownTable(doc, 'Product Analysis', model.productBreakdown, 'Product', y, 'Potential Savings')
  y = breakdownTable(doc, 'Department Analysis', model.departmentBreakdown, 'Department', y)
  // VBU/domain/plan breakdowns only exist on the Cost report's model
  // (buildCostReportModel) — breakdownTable already no-ops on an empty
  // array, so this is a no-op for every other report.
  y = breakdownTable(doc, 'VBU Analysis', model.vbuBreakdown || [], 'VBU', y)
  y = breakdownTable(doc, 'Domain Analysis', model.domainBreakdown || [], 'Domain', y)
  y = breakdownTable(doc, 'License / Plan Analysis', model.planBreakdown || [], 'Plan', y, 'Potential Savings')
  y = userAnalysisTables(doc, model, y)
  activityTable(doc, model, y)
  drawFooterOnAllPages(doc, model.generatedAt)
  return doc
}

export async function downloadReportPdf(model, prefix = 'Internal_IT_Usage_Report') {
  const doc = await buildReportPdf(model)
  const filename = buildReportFilename({ prefix, scope: model.scope, filters: model.rawFilters, ext: 'pdf' })
  downloadBlob(doc.output('blob'), filename)
  return filename
}

// ---- Optimization-specific report (different shape from the general model) ----
export async function buildOptimizationPdf(model) {
  const doc = new jsPDF()
  let y = await reportHeader(doc, model)

  y = sectionHeading(doc, 'Optimization Summary', y)
  autoTable(doc, {
    startY: y, margin: AUTO_TABLE_MARGIN, styles: { fontSize: 10 }, columnStyles: { 0: { fontStyle: 'bold', cellWidth: 70 } },
    body: [
      ['Total Licenses', model.totalLicenses],
      ['Unused Licenses', model.unusedLicenses],
      ['Low Usage Licenses', model.lowUsageLicenses],
      ['High Cost / Low Usage Candidates', model.highCostLowUsageCount],
      ['Potential Monthly Savings', money(model.potentialSavings)],
      ['Potential Annual Savings', money(model.potentialSavingsAnnual)]
    ]
  })
  y = doc.lastAutoTable.finalY + 10

  y = sectionHeading(doc, 'Recommendations for IT Review', y)
  doc.setFontSize(8)
  doc.setTextColor(107, 114, 128)
  doc.text('These are suggestions only — no licenses are removed automatically.', MARGIN, y)
  y += 6
  autoTable(doc, {
    startY: y, margin: AUTO_TABLE_MARGIN, headStyles: { fillColor: BRAND_BLUE }, styles: { fontSize: 8 },
    head: [['User', 'Product', 'Plan', 'Usage Status', 'Estimated Cost', 'Recommendation', 'Potential Savings']],
    body: model.candidates.map((c) => [
      c.name, na(c.product), na(c.plan || c.seat_tier), na(c.usage_status), money(c.potentialSaving), c.recommendation, money(c.potentialSaving)
    ])
  })
  drawFooterOnAllPages(doc, model.generatedAt)
  return doc
}

export async function downloadOptimizationPdf(model) {
  const doc = await buildOptimizationPdf(model)
  const filename = buildReportFilename({ prefix: 'Internal_IT_Optimization_Report', scope: model.scope, filters: model.rawFilters, ext: 'pdf' })
  downloadBlob(doc.output('blob'), filename)
  return filename
}

// ---- Microsoft 365 User Detail export (different shape again — reuses
// reportHeader by conforming to its generic title/generatedAt/scope/etc.
// fields; see src/utils/microsoftReportModels.js for how the model is
// assembled from the /api/microsoft/users/:id response) ----
export async function buildMicrosoftUserPdf(model) {
  const doc = new jsPDF()
  let y = await reportHeader(doc, model)
  const p = model.profile

  y = sectionHeading(doc, 'Profile', y)
  autoTable(doc, {
    startY: y, margin: AUTO_TABLE_MARGIN, styles: { fontSize: 10 }, columnStyles: { 0: { fontStyle: 'bold', cellWidth: 60 } },
    body: [
      ['Display Name', na(p.display_name)], ['Email / UPN', na(p.upn)], ['User ID', na(p.ms_id)],
      ['Job Title', na(p.job_title)], ['Department', na(p.department)], ['Company', na(p.company_name)],
      ['Office', na(p.office_location)], ['Domain', na(p.domain)],
      ['Account Status', p.account_enabled ? 'Enabled' : 'Disabled'],
      ['Manager', na(p.manager_display_name)], ['VBU / Organization', na(p.vbu)]
    ]
  })
  y = doc.lastAutoTable.finalY + 10

  y = sectionHeading(doc, 'Assigned Microsoft 365 Licenses', y)
  if (model.licenses.length) {
    autoTable(doc, { startY: y, margin: AUTO_TABLE_MARGIN, headStyles: { fillColor: BRAND_BLUE }, styles: { fontSize: 9 }, head: [['License (SKU)']], body: model.licenses.map((l) => [na(l.sku_part_number)]) })
    y = doc.lastAutoTable.finalY + 10
  } else {
    doc.setFontSize(9); doc.setTextColor(107, 114, 128); doc.text('No licenses assigned.', MARGIN, y); doc.setTextColor(0, 0, 0); y += 10
  }

  y = sectionHeading(doc, 'Copilot Usage', y)
  if (model.copilot) {
    autoTable(doc, {
      startY: y, margin: AUTO_TABLE_MARGIN, styles: { fontSize: 10 }, columnStyles: { 0: { fontStyle: 'bold', cellWidth: 60 } },
      body: [['Usage (Activity)', na(model.copilot.activity_count)], ['Last Active', na(model.copilot.last_activity)], ['Plan', na(model.copilot.plan)]]
    })
    y = doc.lastAutoTable.finalY + 10
  } else {
    doc.setFontSize(9); doc.setTextColor(107, 114, 128); doc.text('No Copilot usage data available for this user.', MARGIN, y); doc.setTextColor(0, 0, 0); y += 10
  }

  y = ensureSpace(doc, y, 20)
  y = sectionHeading(doc, 'Devices', y)
  if (model.devices.length) {
    autoTable(doc, {
      startY: y, margin: AUTO_TABLE_MARGIN, headStyles: { fillColor: BRAND_BLUE }, styles: { fontSize: 8 },
      head: [['Device', 'OS', 'Compliance', 'Management', 'Last Sync']],
      body: model.devices.map((d) => [na(d.device_name), na(d.operating_system), na(d.compliance_state), na(d.management_state), fmtDate(d.last_sync_at)])
    })
    y = doc.lastAutoTable.finalY + 10
  } else {
    doc.setFontSize(9); doc.setTextColor(107, 114, 128); doc.text('No devices assigned to this user.', MARGIN, y); doc.setTextColor(0, 0, 0); y += 10
  }

  y = ensureSpace(doc, y, 20)
  y = sectionHeading(doc, 'Applications', y)
  if (model.applications.length) {
    autoTable(doc, {
      startY: y, margin: AUTO_TABLE_MARGIN, headStyles: { fillColor: BRAND_BLUE }, styles: { fontSize: 8 },
      head: [['Application', 'Version', 'Device(s)']],
      body: model.applications.map((a) => [na(a.display_name), na(a.version), (a.devices || []).join(', ') || 'N/A'])
    })
    y = doc.lastAutoTable.finalY + 10
  } else {
    doc.setFontSize(9); doc.setTextColor(107, 114, 128)
    doc.text(model.applicationsError ? `Application data unavailable: ${model.applicationsError}` : 'No application data available for this user\'s devices.', MARGIN, y)
    doc.setTextColor(0, 0, 0); y += 10
  }

  if (model.signIns.length) {
    y = ensureSpace(doc, y, 20)
    y = sectionHeading(doc, 'Recent Sign-in Activity', y)
    autoTable(doc, {
      startY: y, margin: AUTO_TABLE_MARGIN, headStyles: { fillColor: BRAND_BLUE }, styles: { fontSize: 8 },
      head: [['Time', 'Application', 'Status']],
      body: model.signIns.slice(0, 20).map((s) => [fmtDate(s.created_at), na(s.app_display_name), na(s.status)])
    })
  }

  drawFooterOnAllPages(doc, model.generatedAt)
  return doc
}

export async function downloadMicrosoftUserPdf(model) {
  const doc = await buildMicrosoftUserPdf(model)
  const filename = buildEntityReportFilename({ prefix: 'Internal_IT_M365_User', name: model.profile.display_name || model.profile.upn || 'User', ext: 'pdf' })
  downloadBlob(doc.output('blob'), filename)
  return filename
}

// ---- Microsoft 365 Application Detail export ----
export async function buildMicrosoftApplicationPdf(model) {
  const doc = new jsPDF()
  let y = await reportHeader(doc, model)
  const s = model.summary

  y = sectionHeading(doc, 'Application Overview', y)
  autoTable(doc, {
    startY: y, margin: AUTO_TABLE_MARGIN, styles: { fontSize: 10 }, columnStyles: { 0: { fontStyle: 'bold', cellWidth: 60 } },
    body: [
      ['Application', na(s.displayName)], ['Publisher(s)', na(s.publishers.join(', '))], ['Platform(s)', na(s.platforms.join(', '))],
      ['Total Device Installs', s.totalDeviceCount.toLocaleString()], ['Detected Versions', s.versionCount],
      ['Unique Devices Linked', s.uniqueLinkedDeviceCount], ['Last Synced', fmtDate(s.lastSyncedAt)]
    ]
  })
  y = doc.lastAutoTable.finalY + 10

  y = sectionHeading(doc, 'Version Breakdown', y)
  autoTable(doc, {
    startY: y, margin: AUTO_TABLE_MARGIN, headStyles: { fillColor: BRAND_BLUE }, styles: { fontSize: 9 },
    head: [['Version', 'Device Count', 'Percentage']],
    body: model.versions.map((v) => [na(v.version), v.deviceCount.toLocaleString(), v.percentage != null ? v.percentage + '%' : 'N/A'])
  })
  y = doc.lastAutoTable.finalY + 10

  y = ensureSpace(doc, y, 20)
  y = sectionHeading(doc, 'Device Installation Details', y)
  if (model.devices.length) {
    autoTable(doc, {
      startY: y, margin: AUTO_TABLE_MARGIN, headStyles: { fillColor: BRAND_BLUE }, styles: { fontSize: 7 },
      head: [['Device', 'Version', 'User', 'OS', 'Compliance', 'Management', 'Last Sync']],
      body: model.devices.map((d) => [na(d.device_name), na(d.application_version), na(d.user_principal_name), na(d.operating_system), na(d.compliance_state), na(d.management_state), fmtDate(d.last_sync_at)])
    })
  } else {
    doc.setFontSize(9); doc.setTextColor(107, 114, 128)
    doc.text(`No device-level installation records linked yet (${s.versionCount - (model.linkageCoverage?.linkedVersions || 0)} of ${s.versionCount} versions not yet linked).`, MARGIN, y)
    doc.setTextColor(0, 0, 0)
  }

  drawFooterOnAllPages(doc, model.generatedAt)
  return doc
}

export async function downloadMicrosoftApplicationPdf(model) {
  const doc = await buildMicrosoftApplicationPdf(model)
  const filename = buildEntityReportFilename({ prefix: 'Internal_IT_M365_Application', name: model.summary.displayName, ext: 'pdf' })
  downloadBlob(doc.output('blob'), filename)
  return filename
}


// ---- Microsoft 365 dedicated-page "Complete Report" — a management-
// friendly summary across every synced dataset (Users/Devices/Applications/
// Licenses/Departments/Groups/Sign-ins/Copilot), reusing the same shared
// header/section/table/footer helpers every other report in this file
// already uses. Not a general per-record dataset dump (that's what each
// view's own CSV/XLSX export in src/utils/datasetExport.js is for) — this
// is the one-page-per-tenant executive summary.
export async function buildMicrosoft365OverviewPdf(model) {
  const doc = new jsPDF()
  let y = await reportHeader(doc, model)

  y = sectionHeading(doc, 'Microsoft 365 Summary', y)
  autoTable(doc, {
    startY: y, margin: AUTO_TABLE_MARGIN, styles: { fontSize: 10 }, columnStyles: { 0: { fontStyle: 'bold', cellWidth: 70 } },
    body: [
      ['Users', model.counts.users], ['Devices', model.counts.devices],
      ['Applications', model.counts.applications], ['Assigned Licenses', model.counts.licenses],
      ['Groups', model.counts.groups], ['Teams', model.counts.teams],
      ['Copilot Users', model.counts.copilotUsers],
      ['Copilot License Active', model.counts.copilotLicenseActive],
      ['Sign-ins (synced period)', model.counts.signIns]
    ]
  })
  y = doc.lastAutoTable.finalY + 10

  if (model.departments.length) {
    y = ensureSpace(doc, y, 20)
    y = sectionHeading(doc, 'Users by Department', y)
    autoTable(doc, {
      startY: y, margin: AUTO_TABLE_MARGIN, headStyles: { fillColor: BRAND_BLUE }, styles: { fontSize: 9 },
      head: [['Department', 'Users']], body: model.departments.map((d) => [na(d.department), d.count])
    })
    y = doc.lastAutoTable.finalY + 10
  }

  if (model.domains.length) {
    y = ensureSpace(doc, y, 20)
    y = sectionHeading(doc, 'Domain Comparison', y)
    autoTable(doc, {
      startY: y, margin: AUTO_TABLE_MARGIN, headStyles: { fillColor: BRAND_BLUE }, styles: { fontSize: 9 },
      head: [['Domain', 'Total Users', 'Active Users']], body: model.domains.map((d) => [na(d.domain), d.totalUsers, d.activeUsers])
    })
    y = doc.lastAutoTable.finalY + 10
  }

  if (model.licenses.length) {
    y = ensureSpace(doc, y, 20)
    y = sectionHeading(doc, 'License Assignment', y)
    autoTable(doc, {
      startY: y, margin: AUTO_TABLE_MARGIN, headStyles: { fillColor: BRAND_BLUE }, styles: { fontSize: 9 },
      head: [['License (SKU)', 'Assigned Users']], body: model.licenses.map((l) => [na(l.sku), l.count])
    })
    y = doc.lastAutoTable.finalY + 10
  }

  if (model.applications?.length) {
    y = ensureSpace(doc, y, 20)
    y = sectionHeading(doc, 'Top Applications', y)
    autoTable(doc, {
      startY: y, margin: AUTO_TABLE_MARGIN, headStyles: { fillColor: BRAND_BLUE }, styles: { fontSize: 9 },
      head: [['Application', 'Publisher', 'Installations']],
      body: model.applications.map((a) => [na(a.display_name), na(a.publisher), a.device_count?.toLocaleString?.() ?? na(a.device_count)])
    })
    y = doc.lastAutoTable.finalY + 10
  }

  if (model.groupsByType?.length) {
    y = ensureSpace(doc, y, 20)
    y = sectionHeading(doc, 'Groups & Teams', y)
    autoTable(doc, {
      startY: y, margin: AUTO_TABLE_MARGIN, headStyles: { fillColor: BRAND_BLUE }, styles: { fontSize: 9 },
      head: [['Type', 'Count']], body: model.groupsByType.map((g) => [na(g.name), g.value])
    })
    y = doc.lastAutoTable.finalY + 10
  }

  if (model.signInsByDay?.length) {
    y = ensureSpace(doc, y, 20)
    y = sectionHeading(doc, 'Sign-ins by Day', y)
    autoTable(doc, {
      startY: y, margin: AUTO_TABLE_MARGIN, headStyles: { fillColor: BRAND_BLUE }, styles: { fontSize: 9 },
      head: [['Day', 'Successful', 'Failed']], body: model.signInsByDay.slice(-15).map((d) => [na(d.day), d.success, d.failure])
    })
    y = doc.lastAutoTable.finalY + 10
  }

  if (model.copilotBreakdown?.length) {
    y = ensureSpace(doc, y, 20)
    y = sectionHeading(doc, 'Copilot — License Status vs Usage Status', y)
    autoTable(doc, {
      startY: y, margin: AUTO_TABLE_MARGIN, headStyles: { fillColor: BRAND_BLUE }, styles: { fontSize: 9 },
      head: [['License Status', 'Usage Status', 'Users']],
      body: model.copilotBreakdown.map((c) => [na(c.licenseStatus), na(c.usageStatus), c.count])
    })
  }

  drawFooterOnAllPages(doc, model.generatedAt)
  return doc
}

export async function downloadMicrosoft365OverviewPdf(model) {
  const doc = await buildMicrosoft365OverviewPdf(model)
  const filename = buildReportFilename({ prefix: 'Internal_IT_M365_Complete_Report', scope: 'complete', filters: [], ext: 'pdf' })
  downloadBlob(doc.output('blob'), filename)
  return filename
}

// ---- Generic single-dataset PDF — the "Specific Reports" (Users/Devices/
// Applications/Licenses/Departments/Groups/Sign-ins/Copilot) in the
// Microsoft 365 page's unified export menu, and reused as-is (nothing here
// is Microsoft-specific) by any other page needing a scoped "dump these
// rows as a branded PDF table" export — e.g. Cost Analytics' By VBU view.
// One table dump reusing the exact same shared header/section/table/footer
// helpers as every other report above, rather than a bespoke report
// function per dataset — the columns/rows/title are all that differ.
export async function buildTabularDatasetPdf({ title, columns, rows, scope, filtersApplied, sources, generatedAt, dataLastUpdated }) {
  const doc = new jsPDF()
  const model = {
    title, generatedAt: generatedAt || new Date().toISOString(), dataLastUpdated: dataLastUpdated || null,
    scope: scope || 'complete', recordCount: rows.length, sources: sources || [{ label: 'Internal IT Dashboard' }], filtersApplied: filtersApplied || []
  }
  let y = await reportHeader(doc, model)
  y = sectionHeading(doc, `${title} (${rows.length.toLocaleString()})`, y)
  autoTable(doc, {
    startY: y, margin: AUTO_TABLE_MARGIN, headStyles: { fillColor: BRAND_BLUE }, styles: { fontSize: 7 },
    head: [columns.map((c) => c.label)],
    body: rows.map((r) => columns.map((c) => na(r[c.key])))
  })
  drawFooterOnAllPages(doc, model.generatedAt)
  return doc
}

export async function downloadTabularDatasetPdf(args) {
  const doc = await buildTabularDatasetPdf(args)
  const prefix = args.filePrefix || `Internal_IT_${args.title.replace(/[^a-zA-Z0-9]+/g, '_')}`
  const filename = buildReportFilename({ prefix, scope: args.scope || 'complete', filters: args.filtersApplied || [], ext: 'pdf' })
  downloadBlob(doc.output('blob'), filename)
  return filename
}
